### ISSUE TITLE
Wrong chain cert in README

### ISSUE THREAD

**Issue by finlay** [CasperVector/emca#1]
Problem resolved by downloading the x3 https://letsencrypt.org/certs/lets-encrypt-x3-cross-signed.pem chain cert. 

The problem was described accurately here: 
https://community.letsencrypt.org/t/solved-not-trusted-on-mobile-maybe-error-setting-up-chain-cert/13316

I think the letsencrypt server reserves the right to update the intermediate chain without warning.

Thanks for the useful code client!

**Comment by CasperVector** [comment]
Fixed just now.  Many thanks :)
