### ISSUE TITLE
Authorization not found or expired

### ISSUE THREAD

**Issue by Teteros** [CasperVector/emca#2]
When attempting to renew a cert for a domain that has expired I get:

./emca.py auth emca.conf; ./emca.py sign emca.conf > serveronly.crt
```
{
  "type": "urn:acme:error:unauthorized",
  "detail": "Error creating new cert :: authorizations for these names not found or expired: mydomain.example.com",
  "status": 403
}
Traceback (most recent call last):
  File "./emca.py", line 192, in <module>
    main(sys.argv)
  File "./emca.py", line 188, in main
    sign_cert(jws, cfg["csr"])
  File "./emca.py", line 165, in sign_cert
    http_except(ret, "signing certificate")
  File "./emca.py", line 20, in http_except
    raise Exception("unexpected HTTP status `%d' %s" % (ret, desc))
Exception: unexpected HTTP status `403' signing certificate
```

Either using old keys or generating a new .csr+keys (and `./emca.py reg emca.conf` them) yields the above message for my domain.

agmt had to be updated as well `agmt = https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf`

Any ideas?

**Comment by CasperVector** [comment]
What's the output for `./emca.py auth emca.conf`?  I am curious about how you became aware that the agreement is outdated.  Also I recently renewed the certificate for a certain server using the old agreement without this issue (perhaps they just feel it is time to really phase out the old agreement now)...  Anyway thanks for the report :)

**Comment by Teteros** [comment]
```
./emca.py auth emca.conf ;echo $?
0
```
IIRC one of the commands (most likely auth or reg) when I was testing last week or so (to avoid rate issues) returned the old agreement notice. After changing it to the new one in the config, `emca.py auth` exits quietly without errors.
Sign fails with the auth not found/expired error.

The http server is not contacted for the acme-challenge, emca stops at the error.

When you were renewing yours, was is past the 90 days expiry deadline? From the looks of it, emca auth is failing... somehow. As LE does not seem to have the auth on record.

The domain is a just a dummy one for dyndns resolution. You could contact me privately and I could change it to point to your IP so you could give it a go if you'd like to debug this?

**Comment by CasperVector** [comment]
Just tested on the server I mentioned above, using the staging ACME server:
* `reg` rejects the old agreement.
* `auth` accepts requests from accounts using the old agreement.
* `auth` prints the server response as expected, and does not give any warning about the agreement.
* `sign` works as expected.

**Comment by CasperVector** [comment]
Modify your `emca.conf` to use the staging server, apply the following patch to `emca.py`, and paste the output of `./emca.py auth emca.conf` here (you might need to somehow redact it):
```diff
--- a/emca.py
+++ b/emca.py
@@ -105,9 +105,11 @@ def list_domains(csr):
         name[4:] for name in m.group(1).decode("UTF-8").split(", ")
         if name.startswith("DNS:")
     )
+    print(domains)
     return domains
 
 def auth_domain(jws, domain, acme, tries, pause):
+    print(domain)
     ret, info, out = http_resp(jws.send("/acme/new-authz", {
         "resource": "new-authz", "identifier": {"type": "dns", "value": domain}
     }))
```

**Comment by Teteros** [comment]
patch -p0 < yourpatch
`patching file emca.py`
git diff HEAD
```
diff --git a/emca.py b/emca.py
index 40ae5f4..99233f7 100755
--- a/emca.py
+++ b/emca.py
@@ -105,9 +105,11 @@ def list_domains(csr):
         name[4:] for name in m.group(1).decode("UTF-8").split(", ")
         if name.startswith("DNS:")
     )
+    print(domains)
     return domains

 def auth_domain(jws, domain, acme, tries, pause):
+    print(domain)
     ret, info, out = http_resp(jws.send("/acme/new-authz", {
         "resource": "new-authz", "identifier": {"type": "dns", "value": domain}
     }))
```

<swapped to staging server>
./emca.py reg emca.conf

```
{
  "id":"<redacted>",
  "key": {
    "kty": "RSA",
    "n": "<redacted>",
    "e": "<redacted>"
  },
  "contact": [],
  "agreement": "https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf",
  "initialIp": "<redacted>",
  "createdAt": "2017-05-16T15:20:49",
  "Status": "valid"
}
```

./emca.py auth emca.conf; ./emca.py sign emca.conf > serveronly.crt

```
[]
{
  "type": "urn:acme:error:unauthorized",
  "detail": "Error creating new cert :: authorizations for these names not found or expired: <redacted>",
  "status": 403
}
Traceback (most recent call last):
  File "./emca.py", line 194, in <module>
    main(sys.argv)
  File "./emca.py", line 190, in main
    sign_cert(jws, cfg["csr"])
  File "./emca.py", line 167, in sign_cert
    http_except(ret, "signing certificate")
  File "./emca.py", line 20, in http_except
    raise Exception("unexpected HTTP status `%d' %s" % (ret, desc))
Exception: unexpected HTTP status `403' signing certificate
```
auth alone with this patch just prints `[]`

**Comment by Teteros** [comment]
it's expected actually, the .csr was generated like so: `openssl req -new -sha512 -key server.key -subj '/CN=mydomain.example.com/O=mydomain.example.com' > server.csr`

it's for a single domain, as suggested by README. There is no DNS: block i.e like with SAN

**Comment by CasperVector** [comment]
I guess the problem should be in either `list_domains()` or your `.csr` file.  Please generate a fake `.csr` file and then paste the output of `openssl req -in fake.csr -noout -text | grep -vE ':[0-9a-f]{2}:$'` (redacted if necessary).
(BTW, SAN is actually supported, though I have not tested it myself.)

**Comment by Teteros** [comment]
`openssl genrsa 4096 > fake.key`
```
Generating RSA private key, 4096 bit long modulus
......++
..................................................................................................................................................................................................................................................................................................................................................................................................................................................................................++
e is 65537 (0x010001)
```
`openssl req -new -sha512 -key fake.key -subj '/CN=example.mydomain.com/O=example.mydomain.com' > fake.csr`

`openssl req -in fake.csr -noout -text | grep -vE ':[0-9a-f]{2}:$'`
```
Certificate Request:
    Data:
        Version: 1 (0x0)
        Subject: CN = example.mydomain.com, O = example.mydomain.com
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (4096 bit)
                Modulus:
                    df:8d:35
                Exponent: 65537 (0x10001)
        Attributes:
            a0:00
    Signature Algorithm: sha512WithRSAEncryption
         c0:a2:d8:45:fb:f9:c4:48
```

real `.csr` only changes the  Subject (CN,O [to point to my domain[), modulus and Sig. Algo fields from this fake.csr grep'd output.

Out of curiousity, is an email required for the reg step? I do not remember if I defined one as it's been a while. I guess I may try a different domain and/or a acme different client and see if I a get similar output perhaps. Thanks for the help so far in debugging this.

**Comment by CasperVector** [comment]
The problem is now found: openssl helpfully prints `CN = example.mydomain.com, O = example.mydomain.com` instead of the old format `CN=example.mydomain.com, O=example.mydomain.com`, and thus breaks `list_domains()`.
A fix is on the way; also may I request the output of `openssl version` to ~~blame~~praise? And the email is not necessary, or otherwise it would be required in `emca.conf`.

EDIT: you can apply this hotfix:
```diff
--- a/emca.py
+++ b/emca.py
@@ -95,7 +95,7 @@ def reg_acct(jws, agmt):
 
 def list_domains(csr):
     domains, out = [], my_run(["openssl", "req", "-in", csr, "-noout", "-text"])
-    m = re.search(br"Subject:.*? CN=([^\s,;/]+)", out)
+    m = re.search(br"Subject:.*? CN *= *([^\s,;/]+)", out)
     m and domains.append(m.group(1).decode("UTF-8"))
     m = re.search(
         br"X509v3 Subject Alternative Name:\s+([^\n]+)\n",
```

**Comment by Teteros** [comment]
Cheers! I just attempted to register a fresh dummy domain on the staging server in the meantime, which failed with the usual 403 code. `./emca.py auth emca.conf` hangs indefinitely, I haven't noticed this before, it supports your finding that list_domains() is it, as I used the same .csr format.

$ openssl version
`OpenSSL 1.1.0e  16 Feb 2017`

it seems this change broke other acme clients such as: https://github.com/Neilpang/acme.sh/issues/578#issuecomment-277508352

**Comment by CasperVector** [comment]
Apply this patch and print the output of `./emca.py auth emca.conf` when it hangs:
```diff
--- a/emca.py
+++ b/emca.py
@@ -134,6 +134,7 @@ def auth_domain(jws, domain, acme, tries, pause):
 
     uri, i = info["Location"], tries
     while i != 0:
+        print(i)
         ret, info, out = http_resp(my_open(uri))
         if ret >= 400:
             http_except(ret,
```

**Comment by Teteros** [comment]
./emca.py auth emca.conf
```
  File "./emca.py", line 138
    ret, info, out = http_resp(my_open(uri))
                                           ^
IndentationError: unindent does not match any outer indentation level
```

**Comment by Teteros** [comment]
Your former (CN*) patch (before last post) prints this:
└> ./emca.py auth emca.conf
```
5
{
  "type": "http-01",
  "status": "valid",
  "uri": "https://acme-staging.api.letsencrypt.org/acme/challenge/<token>",
  "token": "<token>",
  "keyAuthorization": "<auth>",
  "validationRecord": [
    {
      "url": "http://tetesthrowaway.<domain>/.well-known/acme-challenge/<token>",
      "hostname": "tetesthrowaway.<domain>",
      "port": "80",
      "addressesResolved": [
        "<ip>"
      ],
      "addressUsed": "<ip>",
      "addressesTried": []
    }
  ]
}
```
Does not hang, and auth's on staging.

EDIT: not sure why indendation of `print(i)` was incorrent (github copy paste messed it up?), fixed it locally
and amended above

**Comment by CasperVector** [comment]
Sorry, please try again with the updated version of the latest patch...

**Comment by Teteros** [comment]
@CasperVector Edited post with it repatched,  print(i) value is `5`.

**Comment by CasperVector** [comment]
Well, it seems that the ACME server is just hanging for some mysterious reasons :(  You can try changing the account and the domain (eg. using new dummies for both) and see whether this happens again.

**Comment by Teteros** [comment]
It's all good,
```
-    m = re.search(br"Subject:.*? CN=([^\s,;/]+)", out)
+    m = re.search(br"Subject:.*? CN *= *([^\s,;/]+)", out)
```
did the trick, and I'd say you can commit this patch.
Just updated my real, expired cert :+1:
Possibly you were just rate throttled to test yourself :c

Thanks again.

EDIT:
I don't require SAN functionality for multiple domains, however OpenSSL `1.1.0e` _might_ have also broke it, if an implementation existed before.

**Comment by CasperVector** [comment]
Already done in a99e3afb, after the agreement update in 5f3960f2.  Thank you as well :)

**Comment by CasperVector** [comment]
This problem is caused by `=` becoming enclosed by spaces, which does not affect the parsing of SANs.  So if the openssl upstream does not mess with other formats, SAN usage should be hopefully unaffected.
